/**
 * @description - Errors
 * @export
 * @enum {number}
 */
export enum Errors {

  MISSING_ENDPOINT_ARGUMENT,

  MIJIN_ENDPOINT_NEEDED,

  MISSING_IS_COMPLETE_ARGUMENT,

  NETWORK_TYPE_MISMATCHED,

  APOSTILLE_ALREADY_CREATED,

  APOSTILLE_NOT_CREATED,

  AGGREGATE_COMPLETE_NEED_MULTISIG_ACCOUNT,

  AGGREGATE_BOUNDED_NEED_MULTISIG_ACCOUNT,

  FILE_ALREADY_ANNOUNCED,
}
